-- ==============================================================================
-- REM: Phase 5 Modification — Multiple Weekdays & Recurring Task Exceptions
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor > New Query).
-- ==============================================================================

-- 1. Add week_days SMALLINT[] to public.recurring_tasks
ALTER TABLE public.recurring_tasks 
  ADD COLUMN IF NOT EXISTS week_days SMALLINT[];

-- 2. Migrate existing single week_day to week_days array if week_days is NULL
UPDATE public.recurring_tasks
SET week_days = ARRAY[week_day]::SMALLINT[]
WHERE week_days IS NULL AND week_day IS NOT NULL;

-- 3. Constraint: week_days must have between 1 and 7 items when frequency = 'weekly'
ALTER TABLE public.recurring_tasks
  DROP CONSTRAINT IF EXISTS check_week_days_valid;

ALTER TABLE public.recurring_tasks
  ADD CONSTRAINT check_week_days_valid
  CHECK (
    (frequency = 'weekly' AND week_days IS NOT NULL AND array_length(week_days, 1) >= 1 AND array_length(week_days, 1) <= 7)
    OR frequency = 'daily'
  );

-- 4. Create public.recurring_task_exceptions table
-- Prevents deleted recurring occurrences from being regenerated by the sliding window
CREATE TABLE IF NOT EXISTS public.recurring_task_exceptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recurring_task_id UUID NOT NULL REFERENCES public.recurring_tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  occurrence_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT uq_recurring_task_exception_date UNIQUE (recurring_task_id, occurrence_date)
);

ALTER TABLE public.recurring_task_exceptions ALTER COLUMN user_id SET DEFAULT auth.uid();

-- 5. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_recurring_exceptions_task_date
  ON public.recurring_task_exceptions(recurring_task_id, occurrence_date);

CREATE INDEX IF NOT EXISTS idx_recurring_exceptions_user
  ON public.recurring_task_exceptions(user_id);

-- 6. Enable Row Level Security (RLS) on exceptions
ALTER TABLE public.recurring_task_exceptions ENABLE ROW LEVEL SECURITY;

-- 7. RLS Policies for public.recurring_task_exceptions
DROP POLICY IF EXISTS "Users can view own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can view own recurring task exceptions"
  ON public.recurring_task_exceptions
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can insert own recurring task exceptions"
  ON public.recurring_task_exceptions
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can delete own recurring task exceptions"
  ON public.recurring_task_exceptions
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can update own recurring task exceptions"
  ON public.recurring_task_exceptions
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 8. Grants
GRANT ALL ON TABLE public.recurring_task_exceptions TO authenticated;
GRANT ALL ON TABLE public.recurring_task_exceptions TO service_role;
