-- ==============================================================================
-- REM: Phase 5 Recurring Tasks Table & Row Level Security (RLS)
-- Purpose: Persistent recurring task definitions, multiple weekdays, exceptions,
-- and occurrence link on tasks.
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor > New Query).
-- ==============================================================================

-- 1. Create public.recurring_tasks table
CREATE TABLE IF NOT EXISTS public.recurring_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  frequency TEXT NOT NULL CHECK (frequency IN ('daily', 'weekly')),
  week_day SMALLINT CHECK (week_day >= 0 AND week_day <= 6), -- Legacy single weekday
  week_days SMALLINT[], -- Multi-day weekly recurrence: array of 0..6 (0=Sun, 1=Mon, ..., 6=Sat)
  task_time TIME WITHOUT TIME ZONE,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Ensure user_id defaults to auth.uid()
ALTER TABLE public.recurring_tasks ALTER COLUMN user_id SET DEFAULT auth.uid();

-- Add week_days column if table already existed
ALTER TABLE public.recurring_tasks ADD COLUMN IF NOT EXISTS week_days SMALLINT[];

-- Migrate any existing week_day to week_days array
UPDATE public.recurring_tasks
SET week_days = ARRAY[week_day]::SMALLINT[]
WHERE week_days IS NULL AND week_day IS NOT NULL;

-- Constraint: week_days must have between 1 and 7 items when frequency = 'weekly'
ALTER TABLE public.recurring_tasks DROP CONSTRAINT IF EXISTS check_week_days_valid;
ALTER TABLE public.recurring_tasks
  ADD CONSTRAINT check_week_days_valid
  CHECK (
    (frequency = 'weekly' AND week_days IS NOT NULL AND array_length(week_days, 1) >= 1 AND array_length(week_days, 1) <= 7)
    OR frequency = 'daily'
  );

-- 2. Modify public.tasks to link to recurring_tasks
ALTER TABLE public.tasks 
  ADD COLUMN IF NOT EXISTS recurring_task_id UUID REFERENCES public.recurring_tasks(id) ON DELETE SET NULL;

-- 3. Prevent duplicate occurrences at database level (CRITICAL)
-- Only enforces uniqueness when recurring_task_id is NOT NULL, so one-time tasks remain unrestricted
CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_recurring_task_date
  ON public.tasks (recurring_task_id, task_date)
  WHERE recurring_task_id IS NOT NULL;

-- 4. Create public.recurring_task_exceptions table
-- Prevents deleted recurring occurrences from being regenerated by the sliding window
CREATE TABLE IF NOT EXISTS public.recurring_task_exceptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recurring_task_id UUID NOT NULL REFERENCES public.recurring_tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  occurrence_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT uq_recurring_task_exception_date UNIQUE (recurring_task_id, occurrence_date)
);

ALTER TABLE public.recurring_task_exceptions ALTER COLUMN user_id SET DEFAULT auth.uid();

-- 5. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_recurring_tasks_user_active
  ON public.recurring_tasks(user_id, active);

CREATE INDEX IF NOT EXISTS idx_tasks_recurring_task_id
  ON public.tasks(recurring_task_id);

CREATE INDEX IF NOT EXISTS idx_recurring_exceptions_task_date
  ON public.recurring_task_exceptions(recurring_task_id, occurrence_date);

CREATE INDEX IF NOT EXISTS idx_recurring_exceptions_user
  ON public.recurring_task_exceptions(user_id);

-- 6. Explicit Postgres Grants
GRANT USAGE ON SCHEMA public TO authenticated, anon;
GRANT ALL ON TABLE public.recurring_tasks TO authenticated;
GRANT ALL ON TABLE public.recurring_tasks TO service_role;
GRANT ALL ON TABLE public.recurring_task_exceptions TO authenticated;
GRANT ALL ON TABLE public.recurring_task_exceptions TO service_role;

-- 7. Enable Row Level Security (RLS)
ALTER TABLE public.recurring_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recurring_task_exceptions ENABLE ROW LEVEL SECURITY;

-- 8. RLS Policies for public.recurring_tasks
DROP POLICY IF EXISTS "Users can view own recurring tasks" ON public.recurring_tasks;
CREATE POLICY "Users can view own recurring tasks"
  ON public.recurring_tasks FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own recurring tasks" ON public.recurring_tasks;
CREATE POLICY "Users can insert own recurring tasks"
  ON public.recurring_tasks FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own recurring tasks" ON public.recurring_tasks;
CREATE POLICY "Users can update own recurring tasks"
  ON public.recurring_tasks FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own recurring tasks" ON public.recurring_tasks;
CREATE POLICY "Users can delete own recurring tasks"
  ON public.recurring_tasks FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- 9. RLS Policies for public.recurring_task_exceptions
DROP POLICY IF EXISTS "Users can view own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can view own recurring task exceptions"
  ON public.recurring_task_exceptions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can insert own recurring task exceptions"
  ON public.recurring_task_exceptions FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can delete own recurring task exceptions"
  ON public.recurring_task_exceptions FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own recurring task exceptions" ON public.recurring_task_exceptions;
CREATE POLICY "Users can update own recurring task exceptions"
  ON public.recurring_task_exceptions FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 10. Updated_at Trigger for recurring_tasks
DROP TRIGGER IF EXISTS trigger_set_recurring_tasks_updated_at ON public.recurring_tasks;
CREATE TRIGGER trigger_set_recurring_tasks_updated_at
  BEFORE UPDATE ON public.recurring_tasks
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();
